### PR TITLE
reworked simplify vehicle functionality

### PR DESCRIPTION
**Pull request by Please-Pick-a-Name**
its now capable of finding the closest simple body depending on the given vehicle config parts

however the implementation starts turning into chaos dealing with vehicle like the pickup

### CODE REVIEW

**Comment by Please-Pick-a-Name** [comment]
id like input on whatever can be done to make it better

**Comment by lionkor** [comment]
is this ready for review? if so pls mark as ready

**Comment by Please-Pick-a-Name** [comment]
> is this ready for review? if so pls mark as ready

sure i will mark this for review, since im not sure how i want to improve this mess further

**Comment by Starystars67** [comment]
Testing this everything seems to work as expected for me.
I understand your concern about trying to tidy it up however I too am not sure on much that could be done at this point so I am going to move this through.

**Review by Starystars67 — APPROVED** [review]

**Pull request merged**
