### PR TITLE
Fix issue with single quotes in server name & description

### LINKED ISSUE #290: [Bug] Servers with descriptions containing a single quote mark cannot be added to Favorites
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
Servers with descriptions containing a single quote mark (possibly more) cannot be added to Favorites.

**To Reproduce**
1. Host or find a server with a single quote mark in the description.
2. Click the server in the list, then click "Add to Favorites"
3. See server list refresh but server was not added to Favorites

**Expected behavior**
Any server should be able to be added to Favorites no matter what the description contains.

**Desktop (please complete the following information):**
 - OS + Version: W11, latest

**Additional context**
Unknown if a second single quote mark in a description, or other characters, change this observed behavior.

### PR DESCRIPTION
**Pull request by Starystars67**
This PR addresses Issue #290

### CODE REVIEW

**Comment by OfficialLambdax** [comment]
So your code fixes favoriting servers with only a single ' inside servernames. But it brakes when the server only has a single " in their name. So instead of doing some funny string replacing, i now changed it to just base64 encode the server entry before it sends it to MPConfig.

I also added two MPHelper functions that can base64 encode/decode using a recently introduced game libary named mime.

**Comment by Starystars67** [comment]
Hi @OfficialLambdax, thanks for taking a look at this one.

Can you confirm for me what exactly happens now in the event of a single or double quote exisiting?

Thanks

**Review by Starystars67 — COMMENTED** [review]
All looks good codewise.
I cannot approve this PR as I created it though.

@OfficialLambdax maybe you could do that please?

**Review by OfficialLambdax — DISMISSED** [review]

**Comment by Starystars67** [comment]
Hi @OfficialLambdax,

I tested your PR and there was an issue.
I have committed a fix please test and confirm that it works for you too.

Also could you handle the conflicts so it could be merged?

Thanks

**Review by OfficialLambdax — DISMISSED** [review]

**Review by OfficialLambdax — APPROVED** [review]

**Pull request merged**
