### PR TITLE
Content & Safety Filters

### PR DESCRIPTION
**Pull request by Starystars67**
This PR add's text chat filtering at various levels to the users liking.
There is also the ability to add custom options to this.

image

### CODE REVIEW

**Comment by lionkor** [comment]
Any chance we can get a better word list on this?

**Comment by Starystars67** [comment]
> Any chance we can get a better word list on this?

Yes, happy to receive additional commits against this please.

**Comment by lionkor** [comment]
- Poof
- Suck
- crap
- Coon
- jerk (maybe replace with jerkoff and jerk off)
- omg
- poop
- turd
- bloody

and also

- christian
- muslim
etc need to go

**Comment by lionkor** [comment]
- asian
-

**Comment by trebor8820** [comment]
Moderation team to review and provide 5 different lists based on severity.  Estimated deadline for provision of said list Dec 1, following the moderation meeting.

**Comment by Starystars67** [comment]
This still requires the ability to load the txt files.

**Pull request closed without merging**
