### PR TITLE
Fixed chinese translation for the new featured string

### PR DESCRIPTION
**Pull request by Please-Pick-a-Name**
fixed the translation to be a bit more proper
thats it

yeap, thats it

### CODE REVIEW

**Review by OfficialLambdax — APPROVED** [review]
<3

**Comment by Starystars67** [comment]
Wow you are pretty quick on this. Thank you.

I have also just added a new official string too, Would you mind adding that too?
See here for reference: https://github.com/BeamMP/BeamMP/blob/new-server-list/mp_locales/en-US.json#L74

Thank you!

**Comment by Please-Pick-a-Name** [comment]
yeap, done :skull:

**Comment by Starystars67** [comment]
Thank you <3

**Pull request merged**
