### PR TITLE
IPC Communication - Launcher V3

### PR DESCRIPTION
**Pull request by Starystars67**
This code changes the connection from TCP/UDP to IPC which remove the network stack from processing and removes latency.

### CODE REVIEW

**Comment by Starystars67** [comment]
Testing last night with ~5 people gave good stable results.

**Comment by Starystars67** [comment]
Note that this PR requires Launcher V3 and if this gets pushed public the new launcher will need to be released with it.

**Comment by Starystars67** [comment]
Probably worth scheduling this update to be released with the new launcher and update checking system from the backend.

**Comment by 20dka** [comment]
issues so far:
-ping seem to disappear after a while
-leaving a server shows the 'you have been kicked' prompt, sometimes does not actually let you leave
-mods remain after leaving a modded server

**Pull request merged**
