### PR TITLE
Fix for stuck error message on loading popup

### LINKED ISSUE #420: [Bug] Stuck error message on loading popup
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
A received error message on connection to a server is not flushed by the UI. The error will be visible on anew connection even though it shouldn't.
Issue for PR #414

### PR DESCRIPTION
**Pull request by AlexITA1100**
Found a fix for a small UI bug concerning the "LoadingBody" popup.
Steps to reproduce:
- Connect to a server that spits an error (Server full/Connection closed/...);
- The popup will show the error;
- Close the popup;
- Connect to a server, the popup will still show the error message instead of "Connecting to server...". The error message will not be removed until a new message, like "Loading resources...", "Done!", etc., overwrites it;

Video of the behaviour before:

https://github.com/BeamMP/BeamMP/assets/153282308/e62a9ca6-f10f-48f5-8d72-08d132ebe988

With the fix the expected behaviour is the following:
- Connect to a server that spits an error (Server full/Connection closed/...);
- The popup will show the error;
- Close the popup;
- Connect to a server, the popup will show "Connecting to server..." instead of the error.

Video of the behaviour after:

https://github.com/BeamMP/BeamMP/assets/153282308/329b0cd8-541c-4dea-a707-51c0cfc54edc

Notes:
- Sometimes the error is still shown on a new connection but that may be due to a launcher issue.

### CODE REVIEW

**Comment by AlexITA1100** [comment]
fixes #420

**Review by OfficialLambdax — COMMENTED** [review]
This appears to fix half the issue.

Fixed
1. Connect to full Server
2. Receive Error
3. Connect to the same server again
4. No error shown at the start

Bug
1. Connect to full server
2. Receive Error
3. Connect to another Server that you could join
4. Previous error still shown

i tried messing around with this myself, but my angularjs experience is kinda inexistent. So i will neither approve nor request a change

**Comment by Starystars67** [comment]
I have tried this PR out a few times without any issues now. Including the Full to non-full as outlined by @OfficialLambdax.
@AlexITA1100 do you have anything else to add to this or are you happy for it to be merged in?

**Comment by AlexITA1100** [comment]
Nothing to add, if it's good for you it's good for me!

**Review by Starystars67 — DISMISSED** [review]
These feel like a bit of a hacky fix however in the mean time it is a fix non the less.
I will likely revisit this in the ui-revamp.

Thank you Alex.

**Review by Starystars67 — APPROVED** [review]

**Pull request merged**
