### PR TITLE
Remove player list prefix and suffix in UI.lua

### PR DESCRIPTION
**Pull request by 2PXL**

### CODE REVIEW

**Comment by Starystars67** [comment]
Hello @2PXL, thank you for raising this PR.

Please could you provide a description and maybe before & after screenshot showing the change too?
I am fairly sure that I understand exactly what you are intending to do here but would be nice for it to be details for records.

Thanks

**Comment by 2PXL** [comment]
it removes everything that some servers add to the players nametag which can cause quite some clutter.
ba

**Comment by 2PXL** [comment]
forgot to mention that these changes do not affect the additional nametag stuff added by servers, just what shows up in the player list.
m

**Review by daniel-w0 — CHANGES_REQUESTED** [review]
Looks good and functions as expected, just change these lines from:
```lua
username = username..''..player.role.shorttag
```

To:
```lua
username = username .. player.role.shorttag
```

As of right now, it's just concatenating nothing to username with `username = username .. ''`.

**Review by daniel-w0 — APPROVED** [review]
Thanks for the change. I've just tested it again and it works just fine :)

**Review by daniel-w0 — APPROVED** [review]
Looks and works just fine, thanks

**Review by Olrosse — APPROVED** [review]

**Pull request merged**
