### PR TITLE
Fix paint sync + Fix Missing function for vehicleGetSimplified

### LINKED ISSUE #476: [Bug] Client sends invalid paint data of its spawned new vehicle
Since 0.31 the onVehicleSpawned event is called before `extensions.core_vehicle_manager.getVehicleData(gameVehicleID)` is ready to be safely accessed. In this instance `extensions.core_vehicle_manager.getVehicleData(gameVehicleID).config.paints` contains paints that are invalid.

This appears to be a new bug since 0.31
Bug report on the game forum: https://www.beamng.com/threads/onvehiclespawned-is-called-to-early-by-the-game-which-leads-to-invalid-config-data.96054/

Since BeamMP sends the whole config, including the color data, upon the call of this game event, the included config data within the vehicle spawn packet will be partially invalid which leads to different appearances between clients.

### PR DESCRIPTION
**Pull request by Starystars67**
This PR fixes an issue currently in development whereby spawning a vehicle does not work due to vehicleGetSimplified not existing. I have renamed references to this to the correct function name of getVehicleSimplified.

This PR also fixes the paint syncing issue by essentially sending an edit request event message after confirming the vehicle to be local.

### CODE REVIEW

**Review by Mack29446 — CHANGES_REQUESTED** [review]
Broken for me
image

**Comment by Starystars67** [comment]
Hi @Mack29446 thank you for the review however the error you are reporting here references files that are not touched by this PR, I wonder if these occur for you on the default development branch currently for you too?

**Comment by Please-Pick-a-Name** [comment]
im so sorry😭
i might revamp the feature again later, dont put too much effort into it
i was thinking about making it just take in a whole config table and spit out a simplified version of that config, so it can swap multiple part, does part mapping, or additional settings to get rid of light prop etc
i will surely implement what i said here™️

**Comment by Starystars67** [comment]
> im so sorry😭 i might revamp the feature again later, dont put too much effort into it i was thinking about making it just take in a whole config table and spit out a simplified version of that config, so it can swap multiple part, does part mapping, or additional settings to get rid of light prop etc i will surely implement what i said here™️

All good, I just made a small fix :) Also it should have been caught before being merged so that is on us not you!

**Comment by Starystars67** [comment]
I tested this code again and still had no errors as reported by @Mack29446 .

Please can I have additional input by others on this?

**Comment by daniel-w0** [comment]
Seems to be working just fine now 👍

**Pull request merged**
