### PR TITLE
Prevent sort on nil in getFavorites function

### LINKED ISSUE #508: [Bug] Fatal LUA error on empty favorites servers
**Have you read our FAQ/Wiki/#before-you-ask ?**
Yes

**Describe the bug**
If you have no favorite servers, MPConfig.getFavorites will attempt to read a file that does not exist, causing the exception.

**To Reproduce**
1. Ensure you have never had favorite servers;
2. Click the Favorites button from the server list;
3. Check the console (a toast notification will appear as well), you'll find an exception (screenshot below);

**Expected behavior**
Show an empty list or a message saying "You have no favorite servers".

**Screenshots**
immagine

**Desktop (please complete the following information):**
 - Windows 10, BeamNG v0.31.3, BeamMP v4.10.0;

### PR DESCRIPTION
**Pull request by ghost**
This commit adds a nil check for the 'favs' table before attempting to sort it in the getFavorites function. If 'favs' is nil, which occurs when the favorites file is missing, empty, or improperly formatted, the sort operation will be skipped, and an error will be logged. Additionally, 'favs' is initialized to an empty table to prevent downstream errors that expect 'favs' to be a table.

Fixes an issue I was facing. 
```
Fatal Lua Error
string "lua/ge/extensions/MPConfig.lua":186: bad argument #1 to 'sort' (table expected, got nil)
=================== Stack Traceback >> START >> (1) field C function 'sort' (2) Lua field 'getFavorites' at line 186 of chunk 'lua/ge/extensions/MPConfig.lua' Local variables: favs = nil
```

### CODE REVIEW

**Review by Starystars67 — APPROVED** [review]
Perfect small fix, thank you!

**Comment by lionkor** [comment]
@Starystars67 merge please when ready

**Review by OfficialLambdax — APPROVED** [review]
Sorry for the late review, we are very much understaffed in the lua development team at the moment.

looking at it this would have been cleaner by just changing
`local favs = nil` to `local favs = {}`
and then
```
favs = jsonReadFile(favsfile)
if favs == nil then log(.. some error)
```

but looking at the overall `getFavorites()` function i think it could be rewritten all together.
Anyway. Thank you, merging. (:

**Comment by ghost** [comment]
Appreciate the rev!! :)

**Comment by lionkor** [comment]
Thanks for your contribution!

**Pull request merged**
