### PR TITLE
Improve core network socket functionality and performance, including updates to MPDebug teleportation and TCPSocket on MPGameNetwork. Give the user a choice to leave the map when disconnected (allows user to save their configurations).

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
This is untested, I would suggest a good test with the `MPVehicleGE`/`MPDebug` libraries to test this along with the launcher TCP socket itself.

**Comment by ghost** [comment]
I used the best practices as of LuaJIT & Lua 5.1, though the debug update was merely for convenience for someone using the developer console or the API directly (like myself).

**Comment by ghost** [comment]
Keep in mind most edits to the code are, by standard, more readable and intended to help the user.

**Comment by Starystars67** [comment]
Hello @shawnjb , Thank you for coming back and reopening a PR!

Looking over the PR briefly all looks good (I will test it in a little while).  
May I ask, Do you have any performance metrics / statistics to demonstrate improved performance?

Kind regards,

Titch

**Comment by ghost** [comment]
> Hello @shawnjb , Thank you for coming back and reopening a PR!
> 
> Looking over the PR briefly all looks good (I will test it in a little while). May I ask, Do you have any performance metrics / statistics to demonstrate improved performance?
> 
> Kind regards,
> 
> Titch

`pcall` helps to prevent errors from propagating to the calling function, which can cause the program to crash or stop functioning properly. When sending requests over a network, errors can occur due to various reasons such as network issues or server errors. By using `pcall`, the program/runtime can handle these errors in a more contrlled manner, allowing it to continue executing without interruption.

As a side-note, error messages should simply be ignored unless within a development environment. It is best to log errors in a more secure and controlled manner which can be used for debugging and identifying issues within the program without exposing any compromises to the performance of it.

I'd like to also go along about the type assertion and inference which I had implemented into this code. These are crucial for critical operations because they help ensure that the data being operated on is of the expected type, which is important for maintaining the correctness and reliability of the program.

Type assertion is the process of explicitly specifying the type of a variable or value. By using type assertion, the program can ensure that the data being operated on is of the expected type, which can help prevent unexpected errors and ensure the program is functioning as intended. For example, in a financial system, it is critical that the data being operated on, such as transaction amounts or account balances, is of the correct type to ensure accurate calculations and prevent errors that could have severe consequences.

Type inference, on the other hand, is the process of deducing the type of a variable or value automatically by analyzing the context in which it is used. By using type inference, the program can reduce the need for explicit type annotations, which can save time and reduce errors. In critical operations, type inference can be particularly useful for quickly and accurately identifying the type of complex data structures, such as arrays or tables, which can be difficult to manually annotate.

**Comment by Starystars67** [comment]
Hey Shawnjb,
Thank you for writing up a reply and doing so in a way that everyone should be able to understand.

Testing your code, everything seemed to run nicely however there was one issue that I noticed. That was that spawning a vehicle does not get received by the server. As such no players can see my / the users vehicle. Are you able to look into this please?

Kind regards,
Titch

**Comment by ghost** [comment]
> Hey Shawnjb, Thank you for writing up a reply and doing so in a way that everyone should be able to understand.
> 
> Testing your code, everything seemed to run nicely however there was one issue that I noticed. That was that spawning a vehicle does not get received by the server. As such no players can see my / the users vehicle. Are you able to look into this please?
> 
> Kind regards, Titch

Starting tests now.

**Comment by ghost** [comment]
image

Found the problem, creating a patch now.

**Comment by ghost** [comment]
This patch should fix any issues.

**Comment by ghost** [comment]
Made some changes to the dialog box that displays when you are disconnected from a server. This time, when you are disconnected, you are given the option to choose between `Yes` and `No`, using the operating system's dialog box functionality as natively supported by BeamNG.drive

**Comment by ghost** [comment]
image

**Comment by Starystars67** [comment]
Hi Shawnjb, Thank you for working to fix the issue outlined above!

I have now been able to conduct some performance tests and have drawn some conclusions. Do take these as just an input for my system and not necessarily a true reflection of the performance that may be seen for others. As such we will continue to test this with others.

Here is my results:
- Current Public Code (4 players, 4 vehicles (1 each))
BeamMP_PR_Before

- Your PR (4 players, 4 vehicles (1 each))
BeamMP_PR_After

- Current Public Code (4 players, 12 vehicles)
BeamMP_PR_Before_2

- Your PR (4 players, 12 vehicles)
BeamMP_PR_After_2


Please do share your results from your testing too.

Kind regards,
Titch

**Comment by MikeBooon** [comment]
That is a lot of formatting changes

**Comment by ghost** [comment]
I don't know if I want to contribute to a project like this anymore. I apologize for my harsh criticism, but I do not apologize for the words I have been told.

> image

And you really expect me to do so? It's an open source project, and I feel strongly that the behavior of @lionkor towards me was inappropriate and personal. I don't think it's fair for anyone to be treated this way, and I'm concerned about the impact this could have on the overall community of contributors.

@lionkor's behavior crossed the line. I would appreciate it if the project moderators or administrators could look into this issue and take appropriate action to address it. If this behavior is allowed to continue unchecked, it could lead to a toxic atmosphere that drives away potential contributors. Ultimately, I have to decide for myself whether I want to continue contributing to this project, but I hope that steps will be taken to ensure that everyone is treated with the respect they deserve.

**Comment by lionkor** [comment]
@shawnjb If you look through previous few hundred commits, PRs, issues, and conversations in BeamMP script channels, you can see how I interact with people who actually contribute code themselves, respond to questions, and respond meaningfully.

You were warned not to use AI for your contributions, yet:

- we were able to reproduce your discussion points nearly identically using ChatGPT
- some of your changes are utterly meaningless, and you ignore the questions and fail to respond to why you made changes
- the changes that arent completely meaningless are wrong, inconsistent, or (in the case of the PR the screenshot is from) not cross platform (something AI loves to do with underspecified prompts).
- you previously admitted to using some AI to help you write documentation (which means you are aware of how to use it)

I dont see anything saving you on that side.

Furthermore, BeamMP, BeamMP Launcher, and BeamMP Server are *not* open source, they are source available. I **expect** you to know this, given that you changed the formatting of the license of BeamMP Server in your PR, which is the license that literally says "is not open source, is not free software". Unless, of course, you didnt read it, didnt understand it, and changed it with some AI assistant (or by mashing your keyboard) anyway.

> toxic atmosphere that drives away potential contributors

What drives away contributions is people PRing so much garbage that we dont have time to work on actual code anymore.

Don't @ me again, dont keep talking about this, I do not care.

Im always open to review PRs written by humans, who are willing and able to answer super basic questions about the code they submitted.

**Comment by ghost** [comment]
I understand that my code may have had some mistakes due to my naivety, but that does not give anyone the right to berate me. From my perspective, I am not ignoring any advice that could be given to me regarding my mistakes. In fact, the pull request I made has taught me a good measure of what is appropriate to change. When someone submits a pull request with mistakes or naive code, it should be treated with constructive feedback. The goal of contributing is to learn and improve, not to be criticized or discouraged.

**Pull request closed without merging**
