### PR TITLE
Chat ImGui

### PR DESCRIPTION
**Pull request by daniel-w0**
I've moved the chat to an ImGui window instead because it's a lot more customizable, faster and easier to work with.
You can enable it by going into the experimental options and checking the box.

## Bugs
`imgui.SetScrollHereY(1)` isn't working correctly with multi-line messages, I've tried to fix it but was unable to do so.
Maybe someone else can take a [look?](https://github.com/vulcan-dev/BeamMP/blob/bf7d1a34a31faf79be234c12a6408a27f2834ef5/lua/ge/extensions/multiplayer/ui/chat.lua#L87)

### CODE REVIEW

**Comment by O1LER** [comment]
Would it be possible to add an option to change the color of the persons name in the chat? I see that theres a wider gap between individual messages, but its still hard to spot where one message ends and another starts

**Comment by daniel-w0** [comment]
> Would it be possible to add an option to change the color of the persons name in the chat? I see that theres a wider gap between individual messages, but its still hard to spot where one message ends and another starts

Yeah, it is a little difficult to see. I'll fix this later when I'm on

**Comment by Starystars67** [comment]
> > Would it be possible to add an option to change the color of the persons name in the chat? I see that theres a wider gap between individual messages, but its still hard to spot where one message ends and another starts
> 
> Yeah, it is a little difficult to see. I'll fix this later when I'm on

It should be possible to get if they were staff, donator, youtuber whatever from their account if this helps?

**Comment by daniel-w0** [comment]
> > > Would it be possible to add an option to change the color of the persons name in the chat? I see that theres a wider gap between individual messages, but its still hard to spot where one message ends and another starts
> > 
> > Yeah, it is a little difficult to see. I'll fix this later when I'm on
> 
> It should be possible to get if they were staff, donator, youtuber whatever from their account if this helps?

Yeah sure :)

**Comment by Starystars67** [comment]
> > > > Would it be possible to add an option to change the color of the persons name in the chat? I see that theres a wider gap between individual messages, but its still hard to spot where one message ends and another starts
> > > 
> > > 
> > > Yeah, it is a little difficult to see. I'll fix this later when I'm on
> > 
> > 
> > It should be possible to get if they were staff, donator, youtuber whatever from their account if this helps?
> 
> Yeah sure :)

In the mean time maybe the username could be underlined?
This would also work for standard users better too.

**Comment by daniel-w0** [comment]
> > > > > Would it be possible to add an option to change the color of the persons name in the chat? I see that theres a wider gap between individual messages, but its still hard to spot where one message ends and another starts
> > > > 
> > > > 
> > > > Yeah, it is a little difficult to see. I'll fix this later when I'm on
> > > 
> > > 
> > > It should be possible to get if they were staff, donator, youtuber whatever from their account if this helps?
> > 
> > Yeah sure :)
> 
> In the mean time maybe the username could be underlined?

I'll look into making it more readable but I don't think I'll be underlining it. Maybe making it bold with a bigger padding

**Comment by Starystars67** [comment]
Hello, Is there any update on this pull request please?

Kind regards,

**Comment by daniel-w0** [comment]
> Hello, Is there any update on this pull request please?
> 
> Kind regards,

Hello, I've mostly been busy with other things. Hopefully I can get around to working on it again soon though.

Not much needs doing, it was fully functional the last time I used it and I'm not sure what I was working on last.

**Comment by Starystars67** [comment]
Hey, I am hoping to get this or the PR I created from your work merged soon. I am more than happy to merge yours and then add the changes from mine or move my changes to yours first or merge mine #335 . Please let me know how you would like to proceed.

Thanks

**Comment by daniel-w0** [comment]
> Hey, I am hoping to get this or the PR I created from your work merged soon. I am more than happy to merge yours and then add the changes from mine or move my changes to yours first or merge mine #335 . Please let me know how you would like to proceed.
> 
> Thanks

Hello, do what's easiest for you, I'm not too fussed :)

**Comment by Starystars67** [comment]
> > Hey, I am hoping to get this or the PR I created from your work merged soon. I am more than happy to merge yours and then add the changes from mine or move my changes to yours first or merge mine #335 . Please let me know how you would like to proceed.
> > Thanks
> 
> Hello, do what's easiest for you, I'm not too fussed :)

In that case, I will merge yours because I would like to keep the commit history and associated credit. I will then adjust mine to include the changes too. Would you mind adding the Chat history feature before we do that?
If you could also address the outstanding conflicts for me too that would be greatly appreciated!

**Comment by daniel-w0** [comment]
@Starystars67 Should be good to go, everything is fixed and working correctly.
In the future, I would like to make it more customisable (custom context menu's for example. On x server, they can add certain options to do something).

Colors should also be added in the future. I did have it implemented but it didn't wrap well because I was drawing each word separately.

**Comment by Starystars67** [comment]
> @Starystars67 Should be good to go, everything is fixed and working correctly. In the future, I would like to make it more customisable (custom context menu's for example. On x server, they can add certain options to do something).
> 
> Colors should also be added in the future. I did have it implemented but it didn't wrap well because I was drawing each word separately.

Perfect thank you @vulcan-dev , Really appreciate it!
I welcome additional PR's to further improve any aspect of the project :)

I will review and hopefully merge it now.

**Review by Starystars67 — APPROVED** [review]
Great thank you.

Two observations;

1. Are we able to use any of the icons from the map editor rather than re-including icons?
2. Would you mind commenting / documenting your code according to LDoc?

**Comment by daniel-w0** [comment]
> Great thank you.
> 
> Two observations;
> 
> 1. Are we able to use any of the icons from the map editor rather than re-including icons?
> 2. Would you mind commenting / documenting your code according to LDoc?

I have gotten busy again with other bits but I will take a look once I'm free again.
I've also been working on a UIScale slider, it's required a lot of changes but it's almost done. I just need to get the elements on the titlebar vertically centered and then it's perfect.

**Comment by Starystars67** [comment]
> > Great thank you.
> > Two observations;
> > 
> > 1. Are we able to use any of the icons from the map editor rather than re-including icons?
> > 2. Would you mind commenting / documenting your code according to LDoc?
> 
> I have gotten busy again with other bits but I will take a look once I'm free again. I've also been working on a UIScale slider, it's required a lot of changes but it's almost done. I just need to get the elements on the titlebar vertically centered and then it's perfect.

Hey there,

Just hoping to check in on the status of things. 
Do you think this work already here is okay to still merge and then add your extra work later down the road?

Thanks

**Comment by daniel-w0** [comment]
> > > Great thank you.
> > > Two observations;
> > > 
> > > 1. Are we able to use any of the icons from the map editor rather than re-including icons?
> > > 2. Would you mind commenting / documenting your code according to LDoc?
> > 
> > 
> > I have gotten busy again with other bits but I will take a look once I'm free again. I've also been working on a UIScale slider, it's required a lot of changes but it's almost done. I just need to get the elements on the titlebar vertically centered and then it's perfect.
> 
> Hey there,
> 
> Just hoping to check in on the status of things. Do you think this work already here is okay to still merge and then add your extra work later down the road?
> 
> Thanks

Hello,

Everything is good to be merged, there's no issues with the current code.
The only thing people will dislike is that there's no UI Scaling (it's in the newer version). If you want, I can send you the current version on Discord or I can create a new branch for it.

**Comment by Starystars67** [comment]
> Hello,
>
>Everything is good to be merged, there's no issues with the current code.
>The only thing people will dislike is that there's no UI Scaling (it's in the newer version). If you want, I can send you the current >version on Discord or I can create a new branch for it.

Hey! A new branch / PR would be best if that is okay to preserve commit history.
As and when is convenient for you works for me. In the meantime I am going to get this merged finally and we can merge your scaling work when you are ready :)

Thank you again for this work you did and are doing!

**Review by Starystars67 — APPROVED** [review]

**Comment by Starystars67** [comment]
Well this is weird, it seems to think this PR cannot be rebased due to conflicts but I can do a merge commit.
I would rather do a rebase but if you are okay with a merge commit then I will do that. Please let me know which you would rather and I will do that. If you want to rebase too then please can I ask you to address the conflicts whatever they are?

**Comment by daniel-w0** [comment]
Apologies for the delayed resif ponse.
Go ahead and do the rebase you think that's best, I'll deal with the conflicts. I don't see why there would be any, hopefully it's not a lot

**Comment by O1LER** [comment]
Is it possible to remove the windows minimal width and heigth? It bleeds over into other imgui windows and i would like the chat to use less height on my screen

**Comment by Starystars67** [comment]
@vulcan-dev PSA?

**Pull request merged**
