### PR TITLE
Overhaul the Menu UI

### PR DESCRIPTION
**Pull request by daniel-w0**
Preview

It's still not complete, I still need to:
- Fix text wrapping on the 4 bottom cards
- Add styling to the TOS & Login
- Fix some of the button styling

Besides from those minor issues, it works fine and looks nice.
Anyone can feel free to work on those if they want 🙂

### CODE REVIEW

**Comment by Mack29446** [comment]
Since this is still a WIP, I have converted it to a draft PR. It will be marked as ready for review when it's all finished. Thank you for your contributions :D

**Comment by daniel-w0** [comment]
> 

Sounds good, thanks :)
I suppose I can work on it tonight. Hopefully it'll be ready for tomorrow

**Comment by Starystars67** [comment]
Hello @vulcan-dev , Hope you are well :)

Is there any further progress with this?

Kind regards,

**Comment by daniel-w0** [comment]
> Hello @vulcan-dev , Hope you are well :)
> 
> Is there any further progress with this?
> 
> Kind regards,

There has not been any more progress no.
I don't plan on continuing this because they are moving over to Vue and I'm just not a fan with working with the UI (mainly due to how sluggish it feels). Once they begin adding Vue to the menu, that's when I think we should overhaul it.

Feel free to close this if you'd like, maybe you want to keep it open for the future, not sure.

**Comment by Starystars67** [comment]
Hey, can we close this for the time being since we are waiting on the new Vue UI and also I worry that this replaces the games UI which has been raised as an issue in the past with BeamNG? 

That said I think we can start a forum post (on our forum?) and get feedback from the community on what they think. If there is large interest in us producing a new / more modern UI for the game then maybe it will be worth it.

**Comment by Starystars67** [comment]
Closing due to various factors outlined above and the work from the ui-revamp branch.

**Pull request closed without merging**
