### PR TITLE
fixed parts selection highlighting by updating vehicleconfig.js

### LINKED ISSUE #338: BeamMP breaks highlighting and hiding parts [Bug]
since BeamMP is missing the "Highlight Subparts" option in the vehicle editor, it won't allow highlighting and hiding parts.

Vanilla: https://imgur.com/WheYEzG

BeamMP: https://imgur.com/XCJAHcA

### PR DESCRIPTION
**Pull request by Please-Pick-a-Name**
this deals with issue #338, maybe more?

synced (aka changed):
_generateTreeBranch function ???
processPart
selectPart -> selectParts
deselectPart
Vehicleconfig_debug function ???

never learned java script, its quite weird

theres one thing i know i didnt sync, intentionally, the slotPart.value thingy, the vanilla vehicleconfig.js no longer (?) cares about it, but for selfish reasons (i think a server i play in needs that) so i kept it, its just a number

and yes, this fix the highlighting, which i did not test in a real MP enviroment, i dont know the workflow for it :|

### CODE REVIEW

**Comment by Please-Pick-a-Name** [comment]
right, this also deal with #347

**Review by OfficialLambdax — CHANGES_REQUESTED** [review]
Yay thanks. No one seems to have gotten todo this yet. Thanks for doing it! <3

It works so far, just the "Highlight Subparts" option has no function in this PR. If that checkbox is turned off, it will still highlight the parts. If the window is closed and reopened again, the checkbox is also checked again

**Comment by Please-Pick-a-Name** [comment]
> Yay thanks. No one seems to have gotten todo this yet. Thanks for doing it! <3
> 
> It works so far, just the "Highlight Subparts" option has no function in this PR. If that checkbox is turned off, it will still highlight the parts. If the window is closed and reopened again, the checkbox is also checked again

it seems to be a vanilla behaviour😅
unchecking the box only change if the child parts will also be highlighted or not, its not a check box for if its gonna highlight at all
vanilla also dont remember if the box is ticked or not, just goes back to ticked😅
(unless my game is weird)
i have however fixed the highlighting not working when searching parts issue, so thats cool

**Comment by OfficialLambdax** [comment]
I will check this out tommorrow. Thanks alot for looking into it again!

**Review by OfficialLambdax — APPROVED** [review]
You are right, this seems to be a vannilla bug. I ran the game with no mods and this Highlight button is not working as intended. I did not know.

Anyway this pr works nicely! Cannot see any issues with the mod enabled in Singleplayer or Multiplayer. Zero Errors are thrown and the beammp added sync button appears to work (:

**Review by Starystars67 — APPROVED** [review]
LGTM - Not tested but no obvious issues with the code. 

I will pull a copy locally and come back with anything, otherwise I will merge if you are ready for that @Please-Pick-a-Name ?

**Comment by Please-Pick-a-Name** [comment]
> LGTM - Not tested but no obvious issues with the code.
> 
> I will pull a copy locally and come back with anything, otherwise I will merge if you are ready for that @Please-Pick-a-Name ?

yeap, feel free
not that im capable of fixing any issue if there turns out to be some 😅 i just want part highlight 😅

**Comment by Starystars67** [comment]
Testing seemed to have no issues for me. Happy to merge & thank you for fixing this!

**Comment by 2PXL** [comment]
hello its still broken

**Comment by Please-Pick-a-Name** [comment]
> hello its still broken

this is the moment when i have no idea 😓 
you have this commit, yes?

**Comment by 2PXL** [comment]
I only reported this issue I don't know how to fix it.

**Comment by Starystars67** [comment]
> hello its still broken

Hello, This PR has not been pushed out publicly just yet. It is due to be in the coming days.

**Comment by YannD-Deltagon** [comment]
any date for this update ?

**Pull request merged**
