### PR TITLE
Fix: table server list width greater than view on small display

### PR DESCRIPTION
**Pull request by Victortunes**
Simple modification, using flexboxes but does not respect the proportions of the columns

### CODE REVIEW

**Review by Starystars67 — APPROVED** [review]

**Comment by Starystars67** [comment]
Only issue is that this is for the master branch and not our development branch where our work resides.
Would you mind adjusting this PR to be an edit for there?

**Comment by lionkor** [comment]
Thanks very much for your contribution! :)

Seeing as this is your first pull request ever, maybe someone from our team should help with rebasing these changes on the `development` branch!

**Comment by Victortunes** [comment]
Thanks for your replies. I changed the branch, but I don't know if I did it the right way and correctly

**Comment by lionkor** [comment]
It doesn't look correct - you're better off going to the development branch, looking at the file you changed, and making the same change there. Master and development have diverged too much to do it automatically

**Comment by lionkor** [comment]
I fixed this in #233, closing.

**Comment by lionkor** [comment]
Thanks @Victortunes! :) They're still your commits, just did the git magic for you

**Pull request closed without merging**
