### PR TITLE
fix several hardcoded strings, and new simplified chinese translations

### PR DESCRIPTION
**Pull request by Please-Pick-a-Name**
the clear recent string is also added in the en translation file
this pr includes oiler's pr (hi, idk why im everywhere but whatever)

### CODE REVIEW

**Comment by Please-Pick-a-Name** [comment]
guess im fixing more hardcoded strings now, should i split this pr into 2?
also, the entire login page have hardcoded strings, idk what you guys want to do with it?

**Comment by Starystars67** [comment]
Hey, Thank you for seeing this through!

Ideally two PR's would be better however given the size of the edit and the other work here, I think lets just do this as a furthering of the translations system and addition of extra language support.

**Comment by Please-Pick-a-Name** [comment]
there is in total of 20 new string now :skull:
no worry, i added those string in the en files already
- ui.options.multiplayer.launcherPortDefaultPort
- ui.options.multiplayer.nametagFadeIn
- ui.options.multiplayer.nametagFadeOut
- ui.options.multiplayer.tuneBlobColorsHelp
- ui.options.multiplayer.tuneBlobColorsVisible
- ui.options.multiplayer.tuneColorIllegal
- ui.options.multiplayer.tuneColorIllegalHelp
- ui.options.multiplayer.new
- ui.options.multiplayer.experimental
- ui.multiplayer.clearRecent
- ui.multiplayer.pasteFromClipboard
- ui.multiplayer.save
- ui.multiplayer.logout
- ui.multiplayer.login
- ui.multiplayer.register
- ui.multiplayer.playAsGuest
- ui.multiplayer.loginDescription1
- ui.multiplayer.guestDescription1
- ui.multiplayer.iHaveAnAccount
- ui.multiplayer.play

**Comment by Please-Pick-a-Name** [comment]
i think im happy with the translation that i have right now, i will mark this as ready, feel free to complain

**Comment by O1LER** [comment]
@iTeeLion @JamesBlad @YumiNee213 @Desoroxxx @20dka 
If possible, please update your translations to include the 20 newly created strings. In en-US.json they are on lines:
- 26
- 46-47
- 59-60
- 62-63
- 68-69
- 97-107

**Comment by Desoroxxx** [comment]
> If possible, please update your translations to include the 20 newly created strings.


Yes will do this week for the French translation!

**Comment by JamesBlad** [comment]
Of course i will do it on saturday :D

**Comment by O1LER** [comment]
@Starystars67 can we merge this PR?

And the others that add the new lines to the other translations

**Review by Starystars67 — APPROVED** [review]
Thank you for taking the time to contribute towards the project with this!
It is greatly appreciated and I know that the non-english reading community will also appreciate your efforts.

**Pull request merged**
