### PR TITLE
keep text input cursor inside text input field after sending message

### PR DESCRIPTION
**Pull request by StanleyDudek**
very small change, but this is QoL for sending multiple chat messages without having to use the mouse to refocus

### CODE REVIEW

**Comment by StanleyDudek** [comment]
Sorry, I forgot to mention that this is for NEW imgui chat

**Review by OfficialLambdax — DISMISSED** [review]
Does the job as described <3

**Comment by Starystars67** [comment]
Would it be possible to have this as a configurable setting?
This way a user can choose if they want it to remain focused or not.

**Comment by StanleyDudek** [comment]
> Would it be possible to have this as a configurable setting? This way a user can choose if they want it to remain focused or not.

Yes, this now has an option for keeping the cursor active in the chat, works as you requested, looks like this:

image

**Comment by NeotericGamer98** [comment]
Looks very impressive so far.

**Review by Starystars67 — APPROVED** [review]
Nice work @StanleyDudek ,

Thank you for your contributions.

**Pull request merged**
